"""Payload orchestration with two-level caching.

Level 1 (payload cache): an identical request returns the existing payload id
    without doing any work at all.
Level 2 (transform cache): a new request reuses transformed strings for every
    input string seen before; only unseen strings hit the transformer, and
    those are transformed concurrently.

Why the transformer calls are concurrent: the transformer simulates an
external service, so the calls are I/O-bound and parallelizing them is free.
The inputs are deduplicated first so a repeated string within one request is
still transformed only once.
"""

import asyncio
import uuid

from sqlalchemy.exc import IntegrityError
from sqlmodel import select
from sqlmodel.ext.asyncio.session import AsyncSession

from . import logic
from .db import Payload, TransformCache
from .transformer import TransformerClient


async def _load_cached_transforms(
    session: AsyncSession, inputs: list[str]
) -> dict[str, str]:
    keys = [logic.string_key(s) for s in inputs]
    rows = (
        await session.exec(
            select(TransformCache).where(TransformCache.input_hash.in_(keys))
        )
    ).all()
    return {row.input_hash: row.transformed for row in rows}


async def get_or_build_payload(
    list_1: list[str],
    list_2: list[str],
    session: AsyncSession,
    transformer: TransformerClient,
) -> tuple[str, bool]:
    """Build (or reuse) the payload for the given inputs.

    Returns (payload_id, created): created is True when the payload was
    generated by this call, False when an existing identifier was reused.
    """
    key = logic.payload_key(list_1, list_2)

    existing = (
        await session.exec(select(Payload).where(Payload.input_hash == key))
    ).first()
    if existing is not None:
        return existing.id, False

    # Cache miss: transform only strings we have never seen, concurrently.
    unique_inputs = list(dict.fromkeys([*list_1, *list_2]))  # dedupe, keep order
    cached = await _load_cached_transforms(session, unique_inputs)
    missing = [s for s in unique_inputs if logic.string_key(s) not in cached]
    if missing:
        transformed = await asyncio.gather(
            *[transformer.transform(s) for s in missing]
        )
        new_rows = []
        for raw, out in zip(missing, transformed):
            row_key = logic.string_key(raw)
            cached[row_key] = out
            new_rows.append(
                TransformCache(input_hash=row_key, input_text=raw, transformed=out)
            )
        session.add_all(new_rows)
        await session.flush()

    interleaved = logic.interleave(
        [cached[logic.string_key(s)] for s in list_1],
        [cached[logic.string_key(s)] for s in list_2],
    )
    output = logic.format_output(interleaved)

    payload_id = uuid.uuid4().hex
    session.add(Payload(id=payload_id, input_hash=key, output=output))
    try:
        await session.commit()
    except IntegrityError:
        # Lost a race with a concurrent identical request: its row won,
        # so reuse its identifier instead of failing.
        await session.rollback()
        existing = (
            await session.exec(select(Payload).where(Payload.input_hash == key))
        ).first()
        return existing.id, False
    return payload_id, True
